#!/usr/bin/env bash
# MIT © Sindre Sorhus - sindresorhus.com

# git hook to run a command after `git pull` if a specified file was changed
# Run `chmod +x post-merge` to make it executable then put it into `.git/hooks/`.

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

changed() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

if changed 'composer.json'; then
	echo "[composer.json] changed: Installing composer dependencies..."
	composer install
fi